name: "check"
on:
  push:
jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - uses: nextmoose/test-action@ae4d237744a88a2b6ee0bc9654aefd5286714f5a
        with:
          implementation-url: github:nextmoose/scripts
          implementation-postulate: false
          test-url: github:nextmoose/scripts-test
          test-postulate: false
          test-rev: 
          test-defect:
          postulate: true
  check:
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - uses: nextmoose/test-action@ae4d237744a88a2b6ee0bc9654aefd5286714f5a
        with:
          implementation-url: github:nextmoose/scripts
          implementation-postulate: false
          test-url: github:nextmoose/scripts-test
          test-postulate: true
          test-rev: 
          test-defect:
          postulate: true
